Repository BulletTech/BulletTech, pull requests merged in 2021-08, with the labels that each got.

#28 [Main Course] - GA intro
  docs/Main_Course/Analytics_Tools/2021-07-31-GA-Intro.md
Labels: documentation

#26 [Main Course] - Notes of rules of ML2.0
  docs/Main_Course/Data_Analytics/2021-07-24-notes-of-rules-of-ML2.0.md
Labels: documentation

#29 [Main Course] - Useful python packages
  docs/Main_Course/Data_Analytics/2021-08-03-useful-python-packages.md
Labels: documentation

#32 [Foundation] - Fix the bug of nav bar
  material/assets_v2/css/style.css
  material/assets_v2/img/building.jpg
  material/overrides/home.html
Labels: enhancement

#30 [Main Course] - Python tuple sharing
  docs/Main_Course/Coding/2021-08-07-Python-Tuple.md
Labels: documentation

#33 [Main Course] - Loan default
  docs/Main_Course/Data_Analytics/2021-08-08-Loan-Default-Competition-Review.md
Labels: documentation

#34 [Foundation] - Fix the CSS conflicts on Home
  material/assets_v2/css/style.css
  material/overrides/home.html
Labels: bug

#36 [Main Course] - Python list post
  docs/Main_Course/Coding/2021-08-14-Python-list.md
Labels: documentation

#38 [Main Course] - Add Python dict post
  docs/Main_Course/Coding/2021-08-21-Python-Dict.md
Labels: documentation

#37 [Main Course] - sql tips
  docs/Main_Course/Data_Analytics/2021-08-18-Sql-tips.md
Labels: documentation

#39 [Main Course] - Recursion
  docs/Main_Course/Data_Analytics/2021-08-20-practical-recursion-for-data-cleaning.md
Labels: documentation

#40 [Main Course] - Kaggle optiver
  docs/Main_Course/Data_Analytics/2021-08-27-Kaggle-optiver.md
Labels: documentation
